[package]
name = "desktop-app2"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.34.3"
egui_extras = { version = "0.34", features = ["image"] }
serde = { version = "1", features = ["derive"] }
toml = { version = "0.8", features = ["parse"] }
ssh2 = "0.9"
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
bevy = "0.18.1"
